---
# tasks file for myvhost
# 1) 패키지 설치 - httpd
# 2) 서비스 기동 - httpd
# 3) 서비스 설정 - /etc/httpd/conf.d/vhost.conf
# * vhost.conf.j2 -> /etc/httpd/conf.d/vhost.conf
# * notify - handlers
# 4) 서비스 디렉토리 생성 - /var/www/vhosts/ansible1
# 5) /var/www/vhosts/ansible1/index.html 파일 생성


- name: (1) 패키지 설치 - httpd
  yum:
    name: httpd
    state: latest

- name: (2) 서비스 기동 - httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: (3) 서비스 설정 - vhost.conf
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify:
    - restart httpd

- name: (4) 서비스 디렉토리 생성 - /var/www/vhosts/{{ ansible_hostname }}
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory

- name: (5) /var/www/vhosts/{{ ansible_hostname }}/index.html 파일 생성
  copy:
    content: "Welcome to My Web Server - ansible1\n "
    dest: /var/www/vhosts/{{ ansible_hostname }}/index.html