---
# tasks file for myfirewall
# 1) 패키지 설치 - firewalld
# 2) 서비스 기동 - firewalld
# 3) 방화벽 등록 - http

- name: (1) 패키지 설치 - firewalld
  yum:
    name: firewalld
    state: latest

- name: (2) 서비스 기동 - firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
    
- name: firewall service config
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ firewall_service }}"
