---
- name: Time Synchronization
  hosts: datacenters
  
  roles:
    - rhel-system-roles.timesync
  
  post_tasks:
    - name: Set Timezone
      ansible.builtin.timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd
  
  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted