---
- name: Test Web Server
  hosts: webservers
  vars:
  gather_facts: yes
  tasks:
    # 1) 웹 패키지 설치 및 기동
    # * httpd 패키지 설치
    # * httpd 서비스 기동

    # 2) 방화벽 패키지 설치 및 기동 , 서비스 등록
    # * firewalld 패키지 설치
    # * firewalld 서비스 기동
    # * 방화벽 서비스 등록 - http, https

    # 3) 웹 서비스 설정 작업
    # * /var/www/html/index.html

    # 4) 클라이언트에서 웹 요청 테스트

    # * import_playbook 사용
    # * import_tasks, include_tasks 사용

    #===========================================>
    # 1) 웹 패키지 설치 및 기동
    # * httpd 패키지 설치
    # * httpd 서비스 기동
    - name: Include tasks/enviroment.yml
      ansible.builtin.include_tasks: tasks/enviroment.yml
      vars:
        PKG_WEBS:
          - httpd
          - mod_ssl
        SVC_WEB: httpd
        
    # 2) 웹 서비스 설정 작업
    # * /var/www/html/index.html
    - name: import_tasks - tasks/placeholder.yml
      ansible.builtin.import_tasks: tasks/placeholder.yml
      vars:
        indexfile: /var/www/html/index.html
        motdfile: /etc/motd
        

    # 3) 방화벽 패키지 설치 및 기동 , 서비스 등록
    # * firewalld 패키지 설치
    # * firewalld 서비스 기동
    # * 방화벽 서비스 등록 - http, https
    - name: Include tasks - tasks/firewall.yml
      ansible.builtin.include_tasks: tasks/firewall.yml
      vars:
        PKG_FW: firewalld
        SVC_FW: firewalld
        FW_WEBS:
          - http
          - https

# 4) 클라이언트에서 웹 요청 테스트
- name:  Import playbook - plays/test.yml
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    URL: "http://ansible1.example.com"
