#!/bin/bash

# ansible.cfg 만들기

cat << EOF > ansible.cfg
[defaults]
inventory = ./inventory

[privilege_escalation]
become = true

EOF

# inventory 만들기

cat << EOF > inventory
web1
web2
web3
web4

EOF

# playbook.yml 만들기

touch playbook.yml
touch restore_playbook.yml
