---
- name: 방화벽, 웹 서버 설정
  hosts: all
  gather_facts: no
  tasks:
    # 1) 패키지 설치 - httpd, mod_ssl, firewalld
    # 2) 서비스 설정 - /var/www/html/index.html
    # 3) 서비스 기동 - httpd, firewalld
    # 4) 방화벽 등록 - http, https

    - name: httpd package is present
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: present
        
    - name: Correct index.html is present
      copy:
        content: "Welcome to My Server.\n"
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Configuration firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
