---
- name: 복원 작업을 하자
  hosts: all
  tasks:
    - name: 방화벽 내리기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: yes
      loop:
        - http
        - https
    - name: 서비스 내리고
      service:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      loop:
        - httpd
        - firewalld
    
    - name: 쓰레기 파일 삭제하고
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: 패키지 삭제
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - mod_ssl
        - firewalld

    
