---
- name: web-db 복구
  hosts: all
  tasks:
    # 1) 방화벽 포트 닫기 - http, https
    # 2) 웹 서비스 설정 삭제 - /var/www/html/index.html
    # 3) 서비스 내리기
    # 4) 패키지 삭제
    - name: (1) 방화벽 포트 닫기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: yes
      loop:
        - http
        - https
    
    - name: (2) 웹 서비스 설정 삭제
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: (3) 서비스 내리기
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      ignore_errors: yes
      loop:
        - httpd
        - mariadb

    - name: (4) 패키지 삭제
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server

        state: absent



























