---
- name: WEB-DB service

  hosts: all
  tasks:
    # 1) 패키지 설치 - Web(httpd,php,php-mysqlnd,php-pdo), db(mariadb),firewall(firewalld)
    # 2) 웹 서비스 환경 설정 - /var/www/html/index.php
    # 3) 서비스 실행 - firewall, web(httpd), db(mariadb)
    # 4) 방화벽 열어주기 - http, https
    - name: (1) 패키지 설치
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server
          - firewalld
        state: present
      
    - name: (2) 웹 서비스 환경 설정
      get_url:
        url: http://192.168.10.10/index.php
        dest: /var/www/html/index.php
    
    - name: (3) 서비스 실행
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
    
    - name: (4) 방화벽 열어주기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

- name: 웹 서버 테스트
  hosts: localhost
  tasks:
    - name: 인터넷 웹 서버 연결
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200
        