---
- name: 1st play
  hosts: web1
  tasks:
    - name: 패키지 설치
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: latest
    
    - name: 웹 서비스 설정
      copy:
        content: "Welcome To my server\n"
        dest: /var/www/html/index.html
    
    - name: 웹 서비스 기동
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    
    - name: 방화벽 등록
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

- name: 2st play
  hosts: localhost
  tasks:
    - name: web1 웹 페이지 테스트
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200
    #   register: output 
    # - name: 디버그
    #   debug:
    #     var: output












