---
- name: 인트라넷 복원 작업
  hosts: all
  tasks:
    - name: 방화벽 닫기
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - http
        - https
    
    - name: 서비스 닫기
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - httpd
        - firewalld
    
    - name: 잔여 파일 삭제
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 패키지 삭제
      yum:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: absent
      ignore_errors: yes







